# Generated by Django 5.2.6 on 2025-09-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='article_file',
        ),
        migrations.AddField(
            model_name='articles',
            name='content',
            field=models.TextField(default='Default article content'),
            preserve_default=False,
        ),
    ]
